cates = ['scenic spots', 'medical and health', 'domestic services', 'residential area',
             'finance', 'sports and leisure', 'culture and education', 'shopping', 'governments and organizations',
             'corporations', 'catering', 'transportation', 'public services',
             'parking area', 'place of worship']
cates_labels = {
        'scenic spots': ['terrace', 'grandstand', 'pavilion', 'tower', 'triumphal_arch',
                         'farm', 'grave_yard', 'tourism', 'fountain', 'shelter',
                         'bench', 'greenhouse', 'bunker', 'surface'],
        'medical and health': ['hospital', 'clinic', 'doctors', 'dentist', 'pharmacy',
                               'veterinary', 'nursing_home', 'childcare', 'Health_Center',
                               'ambulance', 'first_aid'],
        'domestic services': ['service', 'ventilation_shaft', 'stable', 'slipway', 'kindergarten',
                              'Castle_Hill_Electrical_Supply', 'dressing_room'],
        'residential area': ['apartments', 'house', 'hotel', 'residential',
                             'dormitory', 'terrace', 'pavilion', 'mansion',
                             'hut', 'boathouse', 'apartment', 'townhall', 'semidetached_house',
                             'cabin', 'houseboat', 'gatehouse', 'security_booth'],
        'finance': ['bank', 'stock_exchange', 'money_transfer', 'payment_centre'],
        'sports and leisure': ['theatre', 'sports_centre', 'museum', 'historical', 'stadium',
                               'rest', 'cinema', 'arts_centre', 'detached',
                               'brewery', 'pub', 'food_and_drink', 'cafe',
                               'bar', 'nightclub', 'stripclub', 'biergarten', 'music_venue', 'dojo',
                               'shooting_stand', 'stage', 'karaoke_box'],
        'culture and education': ['school', 'university', 'college', 'historical', 'museum',
                                  'library', 'arts_centre', 'studio', 'research_institute',
                                  'music_school', 'social_centre', 'prep_school', 'school;place_of_worship',
                                  'yes;school', 'stage'],
        'shopping': ['retail', 'commercial', 'supermarket', 'kiosk', 'marketplace'],
        'governments and organizations': ['fire_station', 'storage_tank',
                                          'civic', 'government', 'data_center',
                                          'prison', 'post_office', 'police',
                                          'courthouse', 'events_venue',
                                          'community_centre', 'social_facility', 'recycling',
                                          'mortuary', 'crematorium', 'coworking_space',
                                          'ranger_station', 'waste_disposal', 'security_booth'],
        'corporations': ['office', 'industrial', 'warehouse', 'works', 'car_wash',
                         'car_rental', 'slaughterhouse', 'company', 'manufacture',
                         'coworking_space', 'barn'],
        'catering': ['detached', 'brewery', 'food_and_drink', 'restaurant',
                     'fast_food', 'pub', 'cafe', 'bar', 'food_court', 'biergarten', 'ice_cream', 'plaza',
                     'drinking_water', 'water_tower'],
        'transportation': ['train_station', 'transportation', 'ship', 'hangar',
                           'bridge', 'subway_entrance', 'bicycle_rental', 'boat_rental',
                           'post_depot', 'waste_transfer_station', 'fuel', 'bus_station', 'animal_boarding',
                           'container', 'taxi', 'bus_depot', 'static_caravan', 'houseboat'],
        'public services': ['construction', 'roof', 'shed', 'public', 'toilets', 'triumphal_arch',
                            'mixed_use', 'mixed use', 'ferry_terminal', 'fountain',
                            'shelter', 'post_depot', 'waste_transfer_station',
                            'fuel', 'animal_shelter', 'recycling', 'public_building', 'canopy',
                            'tent', 'lighthouse', 'outdoor_seating'],
        'parking area': ['garage', 'garages', 'parking', 'ruins', 'derelict,_uninhabited',
                         'carport', 'bicycle_parking', 'parking_space', 'motorcycle_parking',
                         'parking_entrance'],
        'place of worship': ['church', 'religious', 'mosque',
                             'synagogue', 'chapel', 'cathedral', 'convent', 'place of worship',
                             'place_of_worship', 'monastery', 'temple', 'school;place_of_worship'],
    }